name: My Petshop Manager

# Development Only Compose File
services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: my_petshop
      POSTGRES_USER: my_pet
      POSTGRES_PASSWORD: my_pet@123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - petshop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 10s
      retries: 3

  spring-app:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
    environment:
      PASSWORD_ENCODER_SECRET_SEED: jSniwziJed8ajw8sx8bw$2i29Han29ej-a
      DATABASE_USERNAME: my_pet
      DATABASE_PASSWORD: my_pet@123
      DATABASE_URL: jdbc:postgresql://database:5432/my_petshop
    ports:
      - 8080:8080
    networks:
      - petshop-network

volumes:
  pgdata:

networks:
  petshop-network:
    driver: bridge
