server:
  servlet:
    session:
      timeout: 60000

spring:
  application:
    name: mypet
  profiles:
    active: production
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  session:
    store-type: jdbc
