spring:
  application:
    name: mypet
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    username: my_pet
    password: myPet@123
    url: jdbc:mysql://localhost:3306/my_pet
  session:
    store-type: jdbc
