spring:
  # Must Change In Production
  password-encoder-seed: MY-PET-SUPER-SECRET-SEED
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  datasource:
    username: my_pet
    password: myPet@123
    url: jdbc:mysql://localhost:3306/my_pet
