spring:
  password-encoder-seed: ${PASSWORD_ENCODER_SECRET_SEED}
  sql:
    init:
      mode: never
  jpa:
    show-sql: false
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
