spring:
  flyway:
    enabled: false
  password-encoder-seed: ${PASSWORD_ENCODER_SECRET_SEED}
  sql:
    init:
      mode: never
  jpa:
    show-sql: false
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://dpg-cua22opopnds73e9p610-a.oregon-postgres.render.com/${DATABASE_NAME}
