CREATE TABLE IF NOT EXISTS `tb_users` (
  `id` VARCHAR(255) PRIMARY KEY NOT NULL,
  `username` VARCHAR(25) UNIQUE NOT NULL,
  `passkey` VARCHAR(255) UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
